name: Production Release PR

on:
  pull_request:
    # Only following types are handled by the action, but one can default to all as well
    types: [opened, reopened, synchronize]
    branches:
      - production

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Release Drafter
        id: drafter
        uses: release-drafter/release-drafter@v6
        with:
          config-file: .github/release-drafter.yml

      - name: Output Generated Release Notes
        run: |
          echo "### Release Notes Draft"
          echo "${{ steps.drafter.outputs.releaseNotes }}"

      - name: Update PR Description With Release Notes
        uses: thomaseizinger/auto-update-pr-description@v2
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          body: |
            ## ðŸš€ Release Notes Preview
            ${{ steps.drafter.outputs.releaseNotes }}
